SELECT nombre FROM tienda.producto;
SELECT nombre, precio FROM tienda.producto;
SELECT * FROM tienda.producto;
SELECT nombre, precio , precio * 1.1 FROM tienda.producto;
SELECT nombre, precio AS euros, precio * 1.1 AS dolares FROM tienda.producto;
SELECT UPPER (nombre), precio FROM tienda.producto;
SELECT LOWER (nombre), precio FROM tienda.producto;
SELECT nombre, SUBSTR(nombre, 1, 2) AS Caracter FROM tienda.fabricante;
SELECT nombre, FORMAT(precio, 0) precio FROM tienda.producto;
SELECT nombre, FORMAT(precio, 2) precio FROM tienda.producto;
SELECT codigo_fabricante FROM tienda.producto;
SELECT codigo_fabricante FROM tienda.producto group by codigo_fabricante;
SELECT nombre FROM tienda.fabricante ORDER BY nombre;
SELECT nombre FROM tienda.fabricante ORDER BY nombre DESC;
SELECT nombre, precio FROM tienda.producto ORDER BY nombre ASC, precio DESC;
SELECT nombre FROM tienda.fabricante LIMIT 0, 5;
SELECT nombre FROM tienda.fabricante LIMIT 4, 2;
SELECT nombre, precio FROM tienda.producto ORDER BY precio LIMIT 0, 1;
SELECT nombre, precio FROM tienda.producto ORDER BY precio DESC LIMIT 0, 1;
SELECT nombre, codigo_fabricante FROM tienda.producto WHERE codigo_fabricante = 2;
SELECT producto.nombre, producto.precio, fabricante.nombre FROM tienda.producto INNER JOIN tienda.fabricante ON producto.codigo_fabricante = fabricante.codigo;
SELECT producto.nombre, producto.precio, fabricante.nombre FROM tienda.producto INNER JOIN tienda.fabricante ON producto.codigo_fabricante = fabricante.codigo ORDER BY fabricante.nombre; 
SELECT producto.codigo, producto.nombre, producto.precio, producto.codigo_fabricante, fabricante.nombre FROM tienda.producto INNER JOIN tienda.fabricante ON producto.codigo_fabricante = fabricante.codigo; 
SELECT producto.nombre, producto.precio, fabricante.nombre FROM tienda.producto INNER JOIN tienda.fabricante ON producto.codigo_fabricante = fabricante.codigo ORDER BY precio LIMIT 0, 1; 
SELECT producto.nombre, producto.precio, fabricante.nombre FROM tienda.producto INNER JOIN tienda.fabricante ON producto.codigo_fabricante = fabricante.codigo ORDER BY precio DESC LIMIT 0, 1; 
SELECT producto.nombre, fabricante.nombre FROM tienda.producto INNER JOIN tienda.fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = "lenovo"; 
SELECT producto.nombre, producto.precio, fabricante.nombre FROM tienda.producto INNER JOIN tienda.fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = "crucial" && producto.precio > 200; 
SELECT apellido1, apellido2, nombre from universidad.persona nombre WHERE tipo = "alumno" ORDER BY apellido1, apellido2, nombre;
SELECT nombre, apellido1, apellido2 from universidad.persona where telefono IS NULL AND tipo = "alumno" ;
SELECT nombre, apellido1, apellido2, fecha_nacimiento from universidad.persona WHERE fecha_nacimiento >= '1999-01-01' AND fecha_nacimiento <= '1999-12-31' AND tipo = "alumno";
SELECT nombre, apellido1, apellido2, nif from universidad.persona where telefono IS NULL AND tipo = "profesor" AND nif LIKE '%K';
SELECT * from universidad.asignatura where cuatrimestre = '1' AND id_grado = '7';
SELECT persona.apellido1, persona.apellido2, persona.nombre, departamento.nombre AS Departamento FROM universidad.persona INNER JOIN universidad.profesor ON persona.id = profesor.id_profesor INNER JOIN universidad.departamento on departamento.id = profesor.id_departamento ORDER BY apellido1, apellido2;
SELECT persona.id, persona.nombre, persona.apellido1, persona.apellido2, asignatura.nombre as asignatura, curso_escolar.anyo_inicio, curso_escolar.anyo_fin FROM universidad.persona INNER JOIN universidad.alumno_se_matricula_asignatura ON persona.id = alumno_se_matricula_asignatura.id_alumno INNER JOIN universidad.asignatura  ON asignatura.id = alumno_se_matricula_asignatura.id_asignatura INNER JOIN universidad.curso_escolar ON curso_escolar.id = alumno_se_matricula_asignatura.id_curso_escolar WHERE nif = '26902806m';
SELECT departamento.nombre AS departamento, grado.nombre AS grado, asignatura.nombre AS asignatura FROM universidad.persona INNER JOIN universidad.profesor ON persona.id = profesor.id_profesor INNER JOIN universidad.departamento ON profesor.id_departamento = departamento.id INNER JOIN universidad.asignatura on profesor.id_profesor = asignatura.id_profesor INNER JOIN universidad.grado ON grado.id = asignatura.id_grado;
SELECT persona.apellido1, persona.apellido2, persona.nombre FROM universidad.persona INNER JOIN universidad.alumno_se_matricula_asignatura ON persona.id = alumno_se_matricula_asignatura.id_alumno INNER JOIN universidad.curso_escolar ON curso_escolar.id = alumno_se_matricula_asignatura.id_curso_escolar WHERE curso_escolar.id = '5' GROUP BY persona.id;
SELECT departamento.nombre AS departamento, persona.apellido1, persona.apellido2, persona.nombre FROM universidad.persona LEFT JOIN universidad.profesor ON persona.id = profesor.id_profesor left JOIN universidad.departamento ON profesor.id_departamento = departamento.id WHERE persona.tipo = 'profesor' ORDER BY persona.apellido1, apellido2;
SELECT departamento.nombre AS departamento, persona.apellido1, persona.apellido2, persona.nombre FROM universidad.persona LEFT JOIN universidad.profesor ON persona.id = profesor.id_profesor left JOIN universidad.departamento ON profesor.id_departamento = departamento.id WHERE persona.tipo = 'profesor' AND departamento.nombre IS NULL ORDER BY persona.apellido1, apellido2;
SELECT departamento.nombre AS departamento_sin_profesor FROM universidad.departamento LEFT JOIN universidad.profesor ON departamento.id = profesor.id_departamento WHERE profesor.id_departamento IS NULL GROUP BY departamento.nombre;
SELECT asignatura.nombre AS asignaturas_sin_profesor FROM universidad.asignatura LEFT JOIN universidad.persona ON asignatura.id_profesor = persona.id WHERE asignatura.id_profesor IS NULL; 
SELECT persona.tipo, COUNT(*) AS Cantidad FROM universidad.persona WHERE persona.tipo = 'alumno' GROUP BY persona.tipo;
SELECT persona.tipo, COUNT(*) as nacidos_1999 FROM universidad.persona WHERE fecha_nacimiento >= '1999-01-01' AND fecha_nacimiento <= '1999-12-31'  AND tipo = "alumno" GROUP BY persona.tipo;
SELECT departamento.nombre, COUNT(*) as profesor_departamento FROM universidad.departamento INNER JOIN universidad.profesor WHERE departamento.id = profesor.id_departamento GROUP BY departamento.nombre ORDER BY COUNT(*) DESC;
SELECT departamento.nombre, COUNT(profesor.id_profesor) AS cantidad_profesores FROM universidad.departamento LEFT JOIN universidad.profesor ON departamento.id = profesor.id_departamento GROUP BY departamento.id;
SELECT grado.nombre as grado, asignatura.nombre as asignatura FROM universidad.grado LEFT JOIN universidad.asignatura ON grado.id = asignatura.id_grado ORDER BY asignatura.nombre;
SELECT persona.id, persona.nombre, persona.apellido1, persona.apellido2, COUNT(asignatura.id_profesor) AS cantidad_asignaturas FROM universidad.persona LEFT JOIN universidad.asignatura ON persona.id = asignatura.id_profesor GROUP BY persona.id ORDER BY COUNT(asignatura.id_profesor) DESC; 
SELECT * FROM universidad.persona WHERE tipo = 'alumno' ORDER BY persona.fecha_nacimiento DESC LIMIT 1;
